[package]
name = "rustybar"
version = "0.3.1"
edition = "2024"
license = "MIT OR Apache-2.0"
description = "A lightweight terminal progress bar for Rust programs"
readme = "README.md"


[dependencies]
crossterm = "0.29.0"

