[package]
name = "rustybar"
version = "0.5.0"
edition = "2024"
license = "MIT OR Apache-2.0"
description = "A lightweight terminal progress bar for Rust programs"
readme = "README.md"


[dependencies]
atty = "0.2.14"
crossterm = "0.29.0"
